org_id                = "default"
project_id            = "default_project"
dev_pipeline_template_name     = "dev-test-deploy"
devops_repository_connector   = "account.acdevopsgithubharnessconnectorssh"
harness_templates_repo_name   = "ac-it-notifications-harness-templates"
harness_templates_branch_name = "main"
